---
# tasks file for apache
# name: Installing Httpd mod_ssl 
- name: Installing httpd httpd-tools and mod_ssl
  yum: name={{ item }} state=latest
  with_items:
  - httpd
  - httpd-tools
  - mod_ssl
  when: ansible_pkg_mgr == "yum"
