---
- name: Installing httpd httpd-tools and mod_ssl
  yum: name={{ item }} state=latest
  with_items:
  - httpd
  - httpd-tools
  - mod_ssl
  - httpd-itk
- template:
    src: roles/apache/templates/vhost.j2
    dest: /etc/httpd/conf.d/{{ domainname }}.conf
    owner: apache
    group: apache
    mode: 0644
