---
- hosts: tier1
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: updating all packages
    yum:
      name: '*'
      state: latest
  - name: copy mod_jk rpm to server
    copy: src=files/epel-release-6-8.noarch.rpm dest=/opt/epel-release-6-8.noarch.rpm
    when: ansible_os_family == 'RedHat'

  - name: Installing epel repository if it is centos 6.8 or Amazon Linux AMI
    yum: name=/opt/epel-release-6-8.noarch.rpm state=present
    when: ansible_os_family == 'RedHat'
#  roles:
#  - apache 
