---
# tasks file for ec2instance---

- name: creating aws ec2 instance
  ec2:
    region: '{{ aws_region }}'
    aws_access_key: '{{ ec2_server_access_key }}'
    aws_secret_key: '{{ ec2_server_secret_key }}'
    key_name: "{{ ec2_ssh_keypair_name  }}"
    group_id: '{{ ec2_security_group }}'
    instance_type: "{{ ec2_instance_type  }}"
    image: "{{ ec2_image_id }}"
    wait: true
    count: "{{ ec2_instance_count }}"
    count_tag:
      Name: "{{ ec2_instance_name }}"
    instance_tags:
      Name: "{{ ec2_instance_name }}"
  register: ec2

- name: print public IP
  debug: msg="{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH
  wait_for:
    host: '{{ item.public_dns_name }}'
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"


- name: Add hosts group temporary inventory group with pem path
  add_host:
    name: '{{ item.public_dns_name }}'
    groups: '{{ ec2_server_group_name }}'
    ansible_ssh_private_key_file: '{{ ec2_server_pem_path }}'
    ansible_ssh_user: '{{ ec2_server_ansible_ssh_user }}'
    domainname: "{{ item.public_dns_name }}"
  with_items: "{{ ec2.instances }}"
  when: ec2_server_pem_path != ''
