---
- name: install mysql-community reposity
  copy: src=files/mysql80-community-release-el6-1.noarch.rpm dest=/opt/mysql80-community-release-el6-1.noarch.rpm
  when: enterprise_linux == 'el6'
 
- name: Installing mysql-community repository 
  yum: name=/opt/mysql80-community-release-el6-1.noarch.rpm state=present
  when: enterprise_linux == 'el6'

- name: install mysql-community reposity
  copy: src=files/mysql80-community-release-el7-1.noarch.rpm dest=/opt/mysql80-community-release-el7-1.noarch.rpm
  when: enterprise_linux == 'el7'

- name: Installing mysql-community repository
  yum: name=/opt/mysql80-community-release-el7-1.noarch.rpm state=present
  when: enterprise_linux == 'el7'

- name: Installing mysql 5.5 version
  yum: name={{ item }} state=present enablerepo=mysql55-community disablerepo=mysql80-community
  with_items:
  - mysql-server
  - MySQL-python
  when: mysql_version == 5.5

- name: Installing mysql 5.6 version
  yum: name={{ item }} state=present enablerepo=mysql56-community disablerepo=mysql80-community
  with_items:
  - mysql-server
  - MySQL-python
  when: mysql_version == 5.5

- name: Installing mysql 5.7 version
  yum: name={{ item }} state=present enablerepo=mysql57-community disablerepo=mysql80-community
  with_items:
  - mysql-server
  - mysql-community-devel
  - python-devel
  - MySQL-python
  when: mysql_version == 5.7

- name: Start service mysqld
  shell: "(mysqld_safe --skip-grant-tables >/dev/null 2>&1 &)"
  register: status

- name: checking status
  debug: msg="{{ status }}"

- name: MySQL | Set the root password.
  mysql_user: name=root host=localhost password={{ mysql_root_password }}

- name: stop mysql background service
  service: name=myqsld state=stopped

- name: starting mysql service normally
  service: name=mysqld state=started enabled=yes
