---
# defaults file for ec2instance
ec2_image_id: ami-14c5486b
aws_region: us-east-1
ec2_instance_count: 1
ec2_ssh_keypair_name: devopsindia
ec2_security_group: sg-05b6d9bab2aae4e6c
ec2_instance_type: t2.micro
ec2_server_access_key: '{{ lookup("env","AWS_ACCESS_KEY_ID") }}'
ec2_server_secret_key: '{{ lookup("env","AWS_SECRET_ACCESS_KEY") }}'
ec2_instance_name: My_Web_server
ec2_server_pem_path: files/privatekey.pem
ec2_server_group_name: 'ec2_server_hosts'
ec2_server_ansible_ssh_user: ec2-user
